### ISSUE TITLE
Question: Relation to NeoLua?

### ISSUE THREAD

**Issue by PatrickKursawe** [moonsharp-devs/moonsharp_org#8]
Hi there,

just a short question: What is the difference to NeoLua? Why should I use this project and not that? Just stumbled upon MoonSharp and got a little confused.

**Comment by LimpingNinja** [comment]
Hey Patrick, this isn't really the appropriate place for this question. Feel free to go to either the forums or discord to get a broader audience (and the right one):

https://discordapp.com/invite/gEEHs6F
https://groups.google.com/forum/#!forum/moonsharp

The forums aren't very active. From what I see at a glance (though I have never touched NeoLua) they are coming at this from different angles, Moonsharp is aiming to provide Lua favoring embedding and making some sacrifices while NeoLua looks to be providing a Lua interpreter following the C-Lua reference.

The way that MoonSharp handles interactivity with .NET  on first glances also appears to be much richer, take a look at these and compare:

http://www.moonsharp.org/dynvalue.html
http://www.moonsharp.org/objects.html
http://www.moonsharp.org/proxy.html
http://www.moonsharp.org/mapping.html 
http://www.moonsharp.org/callback.html

In my personal opinion Moonsharp handles the marriage here much better, and clearly the proxy objects and abstraction can help provide a very rich (with less work) embeddable environment within your application with less work than most other implementations.

YMMV, read through the docs on both and make a decision but join in Discord to ask some of the other developers/users!
